version: '3.7'
services:
  mongodb:
    image: mongo:latest
    container_name: mongodb-cm
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: admin
    ports:
      - 27017:27017
    networks:
      - cm-net
    volumes:
      - mongodb_data:/data/db
volumes:
  mongodb_data:
    driver: local
networks:
  cm-net:
